In [9]:
import numpy as np

$\boldsymbol{X} = \begin{bmatrix}
1&2&3\\
1&2&5\\
1&3&4\\
1&5&9\\
\end{bmatrix}
,　　\boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}
$のとき

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [10]:
# Xの定義
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
]) 

print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [11]:
# yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

print(y)

[[1]
 [5]
 [6]
 [8]]


## Scikit-learnで実装

In [12]:
# Scikit-learnの全ての手法の読み込み
import sklearn

In [13]:
# Windows
#!pip install scikit-learn

# Mac
#! pip3 install scikit-learn

In [14]:
# 重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

In [15]:
# モデルの宣言
model = LinearRegression()

In [17]:
# モデルの学習　←　パラメータの調整
model.fit(X, y)

LinearRegression()

In [19]:
# 調整後のパラメータ
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [20]:
# 切片
model.intercept_

array([-0.14285714])

In [22]:
#　予測精度　←　決定係数
# 0~1の範囲
model.score(X, y)

0.6923076923076923

In [23]:
# 予測値の計算
x = np.array([[1, 2, 3]])

In [26]:
y_pred = model.predict(x)
y_pred

array([[3.]])