## データの読み込み

In [1]:
import numpy as np
import pandas as pd

In [2]:
# CSVの読み込み
df = pd.read_csv('housing.csv')

## 入力変数と出力変数の切り分け

In [3]:
df.head(3)

x1    x2    x3  x4     x5     x6    x7      x8  x9  x10   x11     x12  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296  15.3  396.90   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242  17.8  396.90   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242  17.8  392.83   

    x13     y  
0  4.98  24.0  
1  9.14  21.6  
2  4.03  34.7

In [4]:
# df.iloc[行, 列]

In [5]:
df.iloc[0, 0]

0.00632

In [6]:
X = df.iloc[:, 0:-1]
X

x1    x2     x3  x4     x5     x6    x7      x8  x9  x10   x11  \
0    0.00632  18.0   2.31   0  0.538  6.575  65.2  4.0900   1  296  15.3   
1    0.02731   0.0   7.07   0  0.469  6.421  78.9  4.9671   2  242  17.8   
2    0.02729   0.0   7.07   0  0.469  7.185  61.1  4.9671   2  242  17.8   
3    0.03237   0.0   2.18   0  0.458  6.998  45.8  6.0622   3  222  18.7   
4    0.06905   0.0   2.18   0  0.458  7.147  54.2  6.0622   3  222  18.7   
..       ...   ...    ...  ..    ...    ...   ...     ...  ..  ...   ...   
501  0.06263   0.0  11.93   0  0.573  6.593  69.1  2.4786   1  273  21.0   
502  0.04527   0.0  11.93   0  0.573  6.120  76.7  2.2875   1  273  21.0   
503  0.06076   0.0  11.93   0  0.573  6.976  91.0  2.1675   1  273  21.0   
504  0.10959   0.0  11.93   0  0.573  6.794  89.3  2.3889   1  273  21.0   
505  0.04741   0.0  11.93   0  0.573  6.030  80.8  2.5050   1  273  21.0   

        x12   x13  
0    396.90  4.98  
1    396.90  9.14  
2    392.83  4.03  
3    394.63  2.94  
4    396.90  5.33  
..      ...   ...  
501  391.99  9.67  
502  396.90  9.08  
503  396.90  5.64  
504  393.45  6.48  
505  396.90  7.88  

[506 rows x 13 columns]

In [7]:
y = df.iloc[:, -1]
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: y, Length: 506, dtype: float64

## モデル構築と検証

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
# モデルの宣言
model = LinearRegression()

In [10]:
# モデルの学習
model.fit(X, y)

LinearRegression()

In [11]:
# 検証(決定係数の計算)
model.score(X, y)

0.7406426641094094

## 訓練データ（train）と検証データ（test）を分割
例） 受験勉強用１０年分の過去問を購入

ダメなケース

- 10年分で勉強（学習）
- 10年分で実力テスト(検証)

良いケース

- 前半５年分で勉強(学習)　←　訓練データ
- 後半５年分で実力テスト(検証)　←検証データ

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# 訓練データと検証データの分割
# rando_stateは乱数のシードを固定（再現性）
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1) 

In [14]:
#　モデルの学習
model.fit(X_train, y_train)

LinearRegression()

In [15]:
# 検証　←　検証データ
model.score(X_test, y_test)

0.7209056672661757

In [16]:
# 検証　←　訓練データ
model.score(X_train, y_train)

0.7468316520140625

## 予測値の計算

In [17]:
x = X.iloc[0, :]
x

x1       0.00632
x2      18.00000
x3       2.31000
x4       0.00000
x5       0.53800
x6       6.57500
x7      65.20000
x8       4.09000
x9       1.00000
x10    296.00000
x11     15.30000
x12    396.90000
x13      4.98000
Name: 0, dtype: float64

In [18]:
# 予測値の計算
y_pred = model.predict([x])[0]
y_pred

29.423688469405576

## モデルの保存

In [19]:
# 　今ではもうない
# from sklearn.externals import joblib

import joblib

In [20]:
# モデルの保存
joblib.dump(model, 'model.pkl')

['model.pkl']

## モデルの読み込み

In [21]:
model_new = joblib.load('model.pkl')

In [22]:
x

x1       0.00632
x2      18.00000
x3       2.31000
x4       0.00000
x5       0.53800
x6       6.57500
x7      65.20000
x8       4.09000
x9       1.00000
x10    296.00000
x11     15.30000
x12    396.90000
x13      4.98000
Name: 0, dtype: float64

In [23]:
model_new.predict([x])

array([29.42368847])

## パラメータの確認

In [24]:
# パラメータwの値

# なぜ精度が良かったのかは重みに関係している
# 重みが大きいほど、変数に影響を与えている

model.coef_

array([-8.95714048e-02,  6.73132853e-02,  5.04649248e-02,  2.18579583e+00,
       -1.72053975e+01,  3.63606995e+00,  2.05579939e-03, -1.36602886e+00,
        2.89576718e-01, -1.22700072e-02, -8.34881849e-01,  9.40360790e-03,
       -5.04008320e-01])

In [29]:
# 小数点以下３つ precision=3
# 指数関数での表示が禁止　suppress=Ture

np.set_printoptions(precision=3, suppress=True)

In [30]:
model.coef_

array([ -0.09 ,   0.067,   0.05 ,   2.186, -17.205,   3.636,   0.002,
        -1.366,   0.29 ,  -0.012,  -0.835,   0.009,  -0.504])

In [31]:
df.head(3)

x1    x2    x3  x4     x5     x6    x7      x8  x9  x10   x11     x12  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296  15.3  396.90   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242  17.8  396.90   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242  17.8  392.83   

    x13     y  
0  4.98  24.0  
1  9.14  21.6  
2  4.03  34.7

重み（パラメータw）を見るだけでは、どの変数が影響を与えているかわからない